server:
  port: 8088

jtrace:
  netty:
    port: 4090

logging:
  level:
    root: INFO
influxdb:
  enabled: true
  url: http://192.168.31.99:8086
  username: yachen
  password: chang2001
  database: jtrace